spring.application.name=activity-audit-service
server.port=8001

spring.datasource.url=jdbc:postgresql://localhost:5432/activity_audit_db
spring.datasource.username=postgres
spring.datasource.password=NewPassword123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.data.mongodb.uri=mongodb://localhost:27017/activity_audit_db

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.jwt.secret=ThisIsAReviewSafeJwtSecretKeyForAuditTrail12345
app.jwt.expiration-ms=86400000
